# Course Notes
Use this workspace to take notes, store code snippets, or build your own interactive cheatsheet! For courses that use data, the datasets will be available in the `datasets` folder.

In [59]:
# Import any packages you want to use here
import pandas as pd
import numpy as np
import tensorflow as tf


# Read csv file as credit_card using pandas
credit_card = pd.read_csv('datasets/uci_credit_card.csv')
credit_numpy = credit_card.loc[:,['EDUCATION','MARRIAGE','AGE','BILL_AMT1']].to_numpy()
house = pd.read_csv('datasets/kc_house_data.csv')


          long  sqft_living15  sqft_lot15
0     -122.257           1340        5650
1     -122.319           1690        7639
2     -122.233           2720        8062
3     -122.393           1360        5000
4     -122.045           1800        7503
...        ...            ...         ...
21608 -122.346           1530        1509
21609 -122.362           1830        7200
21610 -122.299           1020        2007
21611 -122.069           1410        1287
21612 -122.299           1020        1357

[21613 rows x 3 columns]


# Introduction to TensorFlow in Python
## Chapter 1 : Introduction to TensorFlow

## Defining data as constants

In [48]:
# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)


 The datatype is: <dtype: 'float64'>

 The shape is: (30000, 4)


## Defining variables

In [11]:
# Define function
def Variable(x):
    return(tf.Variable(x))

In [9]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

 B1:  [1 2 3 4]


## Performing element-wise multiplication

In [13]:
# Define function
def constant(x):
    return(tf.constant(x))

def ones_like(x):
    return(tf.ones_like(x))

def multiply(x, y):
    return(tf.multiply(x, y))

In [16]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))



 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


## Making predictions with matrix multiplication

The matrix of input data, <b>features</b>, contains two columns: education level and age. The target vector, <b>bill</b>, is the size of the credit card borrower's bill. <br> This process will yield a vector of parameters that can be multiplied by the input data to generate predictions</br>
<img src="credit-card.png" 
     width="400" 
     height="500" />

In [18]:
# Define function
def matmul(x, y):
    return (tf.matmul(x, y))

In [19]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


## Optimizing with gradients <br> </br>
<img src="plot.png" 
 />


In [23]:
# Define function
def Variable(x):
    return(tf.Variable(x))

def multiply(x, y):
    return(tf.multiply(x, y))


In [19]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [34]:
# Define function
def multiply(x, y):
    return(tf.multiply(x, y))

def matmul(x, y):
    return(tf.matmul(x, y))

def reshape(model, shape):
    return(tf.reshape(model, shape))

def reduce_sum(output,):
    return(tf.reduce_sum(output,))

model = tf.constant([1, 0, -1], dtype=tf.float32)
letter = np.array([[1,0,1],[1,1,0],[1,0,1]]).astype('float32')

In [44]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

1.0


# Chapter 2 : Linear models
## Load data using pandas

In [46]:
# Import pandas under the alias pd
import pandas as pd

# Assign the path to a string variable named data_path
data_path = 'datasets/kc_house_data.csv'

# Load the dataset as a dataframe named housing
housing = pd.read_csv(data_path)

# Print the price column of housing
print(housing['price'])

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64


## Setting the data type

In [49]:
# Import numpy and tensorflow with their standard aliases
import numpy as np
import tensorflow as tf

# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Print price and waterfront
print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


<img src="Common-Loss-Functions.png" /> <br> </br>
<img src="Common-Loss-Functions2.png" />
     

## Modifying the loss function

In [72]:
features = tf.constant([1., 2., 3., 4., 5.], dtype=tf.float32)
targets = tf.constant([2., 4., 6., 8., 10.], dtype=tf.float32)

# Initialize a variable named scalar
scalar = tf.Variable(1.0, dtype = tf.float32)

# Define the model
def model(scalar, features = features):
  	return scalar * features

# Define a loss function
def loss_function(scalar, features = features, targets = targets):
	# Compute the predicted values
	predictions = model(scalar, features)
    
	# Return the mean absolute error loss
	return keras.losses.mae(targets, predictions)

# Evaluate the loss function and print the loss
print(loss_function(scalar).numpy())

3.0


## Linear Regression
<img src="Linear-Regression.png" />

## Set up a linear regression

In [ ]:
# Define a linear regression model
def linear_regression(intercept, slope, features = size_log):
	return intercept + features*slope

# Set loss_function() to take the variables as arguments
def loss_function(intercept, slope, features = size_log, targets = price_log):
	# Set the predicted values
	predictions = linear_regression(intercept, slope, features)
    
    # Return the mean squared error loss
	return keras.losses.mse(targets, predictions)

# Compute the loss for different slope and intercept values
print(loss_function(0.1, 0.1).numpy())
print(loss_function(0.1, 0.5).numpy())