# Course Notes
Use this workspace to take notes, store code snippets, or build your own interactive cheatsheet! For courses that use data, the datasets will be available in the `datasets` folder.

In [14]:
# Import any packages you want to use here
import pandas as pd
import numpy as np
import tensorflow as tf
import keras

# Read csv file as credit_card using pandas
credit_card = pd.read_csv('datasets/uci_credit_card.csv')
credit_numpy = credit_card.loc[:,['EDUCATION','MARRIAGE','AGE','BILL_AMT1']].to_numpy()

house = pd.read_csv('datasets/kc_house_data.csv')

slmnist = pd.read_csv('datasets/slmnist.csv')

# Introduction to TensorFlow in Python
## Chapter 1 : Introduction to TensorFlow

## Defining data as constants

In [48]:
# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)


 The datatype is: <dtype: 'float64'>

 The shape is: (30000, 4)


## Defining variables

In [11]:
# Define function
def Variable(x):
    return(tf.Variable(x))

In [9]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

 B1:  [1 2 3 4]


## Performing element-wise multiplication

In [13]:
# Define function
def constant(x):
    return(tf.constant(x))

def ones_like(x):
    return(tf.ones_like(x))

def multiply(x, y):
    return(tf.multiply(x, y))

In [16]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))



 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


## Making predictions with matrix multiplication

The matrix of input data, <b>features</b>, contains two columns: education level and age. The target vector, <b>bill</b>, is the size of the credit card borrower's bill. <br> This process will yield a vector of parameters that can be multiplied by the input data to generate predictions</br>
<img src="credit-card.png" 
     width="400" 
     height="500" />

In [18]:
# Define function
def matmul(x, y):
    return (tf.matmul(x, y))

In [19]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


## Optimizing with gradients <br> </br>
<img src="plot.png" 
 />


In [23]:
# Define function
def Variable(x):
    return(tf.Variable(x))

def multiply(x, y):
    return(tf.multiply(x, y))


In [19]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [34]:
# Define function
def multiply(x, y):
    return(tf.multiply(x, y))

def matmul(x, y):
    return(tf.matmul(x, y))

def reshape(model, shape):
    return(tf.reshape(model, shape))

def reduce_sum(output,):
    return(tf.reduce_sum(output,))

model = tf.constant([1, 0, -1], dtype=tf.float32)
letter = np.array([[1,0,1],[1,1,0],[1,0,1]]).astype('float32')

In [44]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

1.0


# Chapter 2 : Linear models
## Load data using pandas

In [46]:
# Import pandas under the alias pd
import pandas as pd

# Assign the path to a string variable named data_path
data_path = 'datasets/kc_house_data.csv'

# Load the dataset as a dataframe named housing
housing = pd.read_csv(data_path)

# Print the price column of housing
print(housing['price'])

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64


## Setting the data type

In [49]:
# Import numpy and tensorflow with their standard aliases
import numpy as np
import tensorflow as tf

# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Print price and waterfront
print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


<img src="Common-Loss-Functions.png" /> <br> </br>
<img src="Common-Loss-Functions2.png" />
     

## Modifying the loss function

In [72]:
features = tf.constant([1., 2., 3., 4., 5.], dtype=tf.float32)
targets = tf.constant([2., 4., 6., 8., 10.], dtype=tf.float32)

# Initialize a variable named scalar
scalar = tf.Variable(1.0, dtype = tf.float32)

# Define the model
def model(scalar, features = features):
  	return scalar * features

# Define a loss function
def loss_function(scalar, features = features, targets = targets):
	# Compute the predicted values
	predictions = model(scalar, features)
    
	# Return the mean absolute error loss
	return keras.losses.mae(targets, predictions)

# Evaluate the loss function and print the loss
print(loss_function(scalar).numpy())

3.0


## Linear Regression
<img src="Linear-Regression.png" />

## Set up a linear regression

In [ ]:
# Define a linear regression model
def linear_regression(intercept, slope, features = size_log):
	return intercept + features*slope

# Set loss_function() to take the variables as arguments
def loss_function(intercept, slope, features = size_log, targets = price_log):
	# Set the predicted values
	predictions = linear_regression(intercept, slope, features)
    
    # Return the mean squared error loss
	return keras.losses.mse(targets, predictions)

# Compute the loss for different slope and intercept values
print(loss_function(0.1, 0.1).numpy())
print(loss_function(0.1, 0.5).numpy())

result is
~~~ python
output:
    145.44653
    71.866
~~~

## Train a linear model

In [ ]:
# Initialize an Adam optimizer with a learning rate of 0.5.
opt = keras.optimizers.Adam(0.5)

for j in range(100):
	# Apply minimize, pass the loss function, and supply the variables
	opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])

	# Print every 10th value of the loss
	if j % 10 == 0:
		print(loss_function(intercept, slope).numpy())

# Plot data and regression line
plot_results(intercept, slope)

result is
~~~ python
output:
    9.669482
    11.726698
    1.1193314
    1.6605737
    0.7982884
    0.8017316
    0.6106565
    0.59997976
    0.5811015
    0.5576158
~~~

<img src="Fitted-Regression-Line.png" />


## Multiple linear regression

In [ ]:
params = tf.Variable([0.1, 0.05, 0.02], dtype=tf.float32)

# Define the linear regression model
def linear_regression(params, feature1 = size_log, feature2 = bedrooms):
	return params[0] + feature1*params[1] + feature2*params[2]

# Define the loss function
def loss_function(params, targets = price_log, feature1 = size_log, feature2 = bedrooms):
	# Set the predicted values
	predictions = linear_regression(params, feature1, feature2)
  
	# Use the mean absolute error loss
	return keras.losses.mae(targets, predictions)

# Define the optimize operation
opt = keras.optimizers.Adam()

# Perform minimization and print trainable variables
for j in range(10):
	opt.minimize(lambda: loss_function(params), var_list=[params])
	print_results(params)

result is
~~~ python
output:
    loss: 12.418, intercept: 0.101, slope_1: 0.051, slope_2: 0.021
    loss: 12.404, intercept: 0.102, slope_1: 0.052, slope_2: 0.022
    loss: 12.391, intercept: 0.103, slope_1: 0.053, slope_2: 0.023
    loss: 12.377, intercept: 0.104, slope_1: 0.054, slope_2: 0.024
    loss: 12.364, intercept: 0.105, slope_1: 0.055, slope_2: 0.025
    loss: 12.351, intercept: 0.106, slope_1: 0.056, slope_2: 0.026
    loss: 12.337, intercept: 0.107, slope_1: 0.057, slope_2: 0.027
    loss: 12.324, intercept: 0.108, slope_1: 0.058, slope_2: 0.028
    loss: 12.311, intercept: 0.109, slope_1: 0.059, slope_2: 0.029
    loss: 12.297, intercept: 0.110, slope_1: 0.060, slope_2: 0.030
~~~

<img src="batch.png" />

## Preparing to batch train

In [11]:
# Define the intercept and slope
intercept = tf.Variable(10.0, dtype=tf.float32)
slope = tf.Variable(0.5, dtype=tf.float32)

# Define the model
def linear_regression(intercept, slope, features):
	# Define the predicted values
	return intercept + slope*features

# Define the loss function
def loss_function(intercept, slope, targets, features):
	# Define the predicted values
	predictions = linear_regression(intercept, slope, features)
    
 	# Define the MSE loss
	return keras.losses.mse(targets, predictions)

## Training a linear model in batches

In [13]:
intercept = tf.Variable(10.0, dtype=tf.float32)
slope = tf.Variable(0.5, dtype=tf.float32)

# Initialize Adam optimizer
opt = keras.optimizers.Adam()

# Load data in batches
for batch in pd.read_csv('datasets/kc_house_data.csv', chunksize=100):
	size_batch = np.array(batch['sqft_lot'], np.float32)

	# Extract the price values for the current batch
	price_batch = np.array(batch['price'], np.float32)

	# Complete the loss, fill in the variable list, and minimize
	opt.minimize(lambda: loss_function(intercept, slope, price_batch, size_batch), var_list=[intercept, slope])

# Print trained parameters
print(intercept.numpy(), slope.numpy())

10.217888 0.7016001
